"""add writer column with server default

Revision ID: 664ea030f71b
Revises: 1802a52f55f8
Create Date: 2025-06-07 14:25:38.642044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664ea030f71b'
down_revision: Union[str, None] = '1802a52f55f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('writer', sa.String(), server_default='Unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'writer')
    # ### end Alembic commands ###
